name: Terraform Plan (PR)

on:
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.3.1
        with:
          tflint_version: v0.64.0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Initialize TFLint plugins
        run: tflint --init

      - name: TFLint
        run: tflint --recursive

      - name: Install Checkov
        run: python -m pip install --disable-pip-version-check checkov==3.3.0

      - name: Checkov
        run: >-
          checkov -d .
          --framework terraform
          --skip-path .terraform
          --compact
          --quiet

      - name: Terraform Plan (dev)
        run: terraform plan -var-file=env/dev.tfvars

